### PR TITLE
Construct CartAPI URL from OS environment variables

### PR DESCRIPTION
**Pull request by markborkum**
### Description

This pull request modifies the constructors for the `Downloader` and `CartAPI` classes so that CartAPI URLs are automatically constructed from either user-specified keyword arguments or OS environment variables.

The intent is that the type signature for the constructor for the `Downloader` class should resemble that of the [`Uploader`](https://github.com/pacifica/pacifica-python-uploader/blob/master/pacifica/uploader/uploader.py) (e.g., use keyword arguments to specify and/or construct URLs).

Changes:

- Added `CommonBase` class using code from https://github.com/pacifica/pacifica-python-uploader/blob/master/pacifica/uploader/common/__init__.py.
- Removed `auth` property from `Downloader` class. For a given instance `d`, use `d.cart_api._auth` instead of `d.auth`.

### Issues Resolved

n/a

### Check List

- [x] All tests pass. See <https://github.com/pacifica/pacifica-docs/blob/master/development/TESTING.md>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by markborkum** [comment]
@dmlb2000 In https://github.com/pacifica/pacifica-python-downloader/pull/15/files#diff-d8e165b4149566ddfdab844d646f4d6fR51, the prefix for environment variables for the `CartAPI` class is "CART". Is this correct?

**Comment by dmlb2000** [comment]
@markborkum We've been standardizing on `CARTD`

**Comment by markborkum** [comment]
@dmlb2000 Also, should we take the opportunity to add more `LOGGER.debug(...)` statements to the `CartAPI` class (e.g., the `setup_cart` and `wait_for_cart` instance methods)?

**Comment by dmlb2000** [comment]
@markborkum Yes more logging the better really.

**Comment by markborkum** [comment]
@dmlb2000 CI is failing due to `autopep8`. Any ideas?

**Comment by dmlb2000** [comment]
@markborkum Yes, autopep8 is kinda lame, I would look for long lines and split them up...

```
foo(a, b, c, d, e)
```
becomes
```
foo(
    a,
    b,
    c,
    d,
    e,
)
```

**Comment by markborkum** [comment]
@dmlb2000 Ready for review.

**Pull request merged**
